# Generated by Django 4.0 on 2024-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program_picture', models.ImageField(blank=True, null=True, upload_to='program_pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Programms',
        ),
    ]
