# Generated by Django 4.0 on 2024-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0004_workoutprogram_program_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='program_picture',
            field=models.ImageField(blank=True, null=True, upload_to='program_pictures/'),
        ),
    ]
