# Generated by Django 4.0 on 2024-03-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0005_alter_workoutprogram_program_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sport_type', models.CharField(max_length=50)),
                ('exercise_picture', models.ImageField(blank=True, null=True, upload_to='exercise_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseWorkoutProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programms.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programms.workoutprogram')),
            ],
        ),
    ]
